# Generated by Django 3.1.2 on 2020-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_matkul', models.CharField(max_length=64)),
                ('kode_matkul', models.CharField(max_length=10)),
                ('jumlah_sks', models.PositiveIntegerField()),
                ('dosen_pengajar', models.CharField(max_length=64)),
                ('deskripsi', models.TextField(max_length=200)),
                ('ruang_kelas', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=10)),
            ],
        ),
    ]
