# Generated by Django 3.1.2 on 2020-10-14 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0002_auto_20201014_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='semester_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='matkul_semester', to='matkul.semester'),
            preserve_default=False,
        ),
    ]
