# Generated by Django 3.1.2 on 2020-10-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0003_matakuliah_semester_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliah',
            old_name='semester_id',
            new_name='term',
        ),
    ]
