# Generated by Django 3.1.2 on 2020-10-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0004_auto_20201014_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='semester_id',
        ),
    ]
