# Generated by Django 3.1.2 on 2020-10-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0005_auto_20201014_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='TugasMatkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_tugas', models.TextField(max_length=100)),
                ('deadline', models.DateTimeField()),
                ('matkul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matkul.matakuliah')),
            ],
        ),
    ]
