# Generated by Django 3.1.2 on 2020-10-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0006_tugasmatkul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugasmatkul',
            name='matkul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_matkul', to='matkul.matakuliah'),
        ),
    ]
