# Generated by Django 3.1.2 on 2020-10-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0008_auto_20201016_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_id',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')]),
        ),
    ]
